export const ingredientsData = [
  {
    id: 1,
    name: "1st Class Flour",
    category: "Flour",
    currentQuantity: 320,
    initialQuantity: 500,
    unit: "kg",
    unitPrice: 52,
    reorderLevel: 100,
  },
  {
    id: 2,
    name: "3rd Class Flour",
    category: "Flour",
    currentQuantity: 650,
    initialQuantity: 800,
    unit: "kg",
    unitPrice: 38,
    reorderLevel: 150,
  },
  {
    id: 3,
    name: "Active Dry Yeast",
    category: "Leavening",
    currentQuantity: 32,
    initialQuantity: 50,
    unit: "kg",
    unitPrice: 180,
    reorderLevel: 10,
  },
  {
    id: 4,
    name: "Granulated Sugar",
    category: "Sweeteners",
    currentQuantity: 210,
    initialQuantity: 300,
    unit: "kg",
    unitPrice: 65,
    reorderLevel: 50,
  },
  {
    id: 5,
    name: "Unsalted Butter",
    category: "Dairy",
    currentQuantity: 45,
    initialQuantity: 100,
    unit: "kg",
    unitPrice: 320,
    reorderLevel: 30,
  },
  {
    id: 6,
    name: "Eggs",
    category: "Dairy",
    currentQuantity: 580,
    initialQuantity: 1000,
    unit: "pcs",
    unitPrice: 8,
    reorderLevel: 200,
  },
  {
    id: 7,
    name: "Milk Powder",
    category: "Dairy",
    currentQuantity: 60,
    initialQuantity: 80,
    unit: "kg",
    unitPrice: 290,
    reorderLevel: 20,
  },
  {
    id: 8,
    name: "Baking Soda",
    category: "Leavening",
    currentQuantity: 15,
    initialQuantity: 30,
    unit: "kg",
    unitPrice: 120,
    reorderLevel: 10,
  },
  {
    id: 9,
    name: "Brown Sugar",
    category: "Sweeteners",
    currentQuantity: 180,
    initialQuantity: 250,
    unit: "kg",
    unitPrice: 58,
    reorderLevel: 40,
  },
  {
    id: 10,
    name: "Vanilla Extract",
    category: "Flavoring",
    currentQuantity: 12,
    initialQuantity: 20,
    unit: "L",
    unitPrice: 950,
    reorderLevel: 5,
  },
  {
    id: 11,
    name: "Baking Powder",
    category: "Leavening",
    currentQuantity: 20,
    initialQuantity: 40,
    unit: "kg",
    unitPrice: 140,
    reorderLevel: 10,
  },
  {
    id: 12,
    name: "Shortening",
    category: "Fat",
    currentQuantity: 70,
    initialQuantity: 100,
    unit: "kg",
    unitPrice: 240,
    reorderLevel: 25,
  },
  {
    id: 13,
    name: "Cocoa Powder",
    category: "Flavoring",
    currentQuantity: 33,
    initialQuantity: 50,
    unit: "kg",
    unitPrice: 310,
    reorderLevel: 15,
  },
  {
    id: 14,
    name: "Vegetable Oil",
    category: "Fat",
    currentQuantity: 90,
    initialQuantity: 150,
    unit: "L",
    unitPrice: 110,
    reorderLevel: 30,
  },
  {
    id: 15,
    name: "Salt",
    category: "Seasoning",
    currentQuantity: 100,
    initialQuantity: 150,
    unit: "kg",
    unitPrice: 22,
    reorderLevel: 40,
  },
  {
    id: 16,
    name: "Cornstarch",
    category: "Thickener",
    currentQuantity: 45,
    initialQuantity: 70,
    unit: "kg",
    unitPrice: 48,
    reorderLevel: 20,
  },
];
